### PR TITLE
Create api and Deploy on AWS EC2

### PR DESCRIPTION
**Pull request by Novsun30**
李育霖:
http://52.69.110.95:3000/api/attractions?page=1
http://52.69.110.95:3000/api/attractions?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80
http://52.69.110.95:3000/api/attractions?page=0&keyword=%E5%8C%97
http://52.69.110.95:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Some issues below:

1. `images` field of attraction should be an one-dimension string array where every image URL of attraction should be a element in this array. For example: `["Image URL 1", "Image URL 2", ...]`
2. http://52.69.110.95:3000/api/categories should be an one-dimension array containing distinct attraction category names.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1 is OK.

But http://52.69.110.95:3000/api/categories should response DISTINCT category names, which means without repetition.

**Comment by Novsun30** [comment]
oops, I got it
This time should be ok

**Review by cwpeng — APPROVED** [review]
OK. Done.

Futher suggest using `GROUP_CONCAT` and `JOIN` to get attraction data and images all at once, not one by one.

**Comment by Novsun30** [comment]
Roger that 🙆‍♂️ 
Thank you teacher!

**Pull request merged**
